[env:adafruit_trellis_m4]
platform = atmelsam
board = adafruit_trellis_m4
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit NeoTrellis M4 Library
  adafruit/Adafruit TinyUSB Library
  adafruit/Adafruit SPIFlash
  adafruit/Adafruit ZeroTimer Library

build_flags =
  -DUSB_MANUFACTURER="\"LoFiSampler\""
  -DUSB_PRODUCT="\"NTM4 Sampler\""
